name: flutter_bloc_clean_architecture_news_guide
description: "Guide: News App using Bloc State Management + Clean Architecture"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.4
  bloc: ^8.1.4
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Network & HTTP
  dio: ^5.4.3
  internet_connection_checker: ^1.0.0+1
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Utilities
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  # URL Launcher
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^5.0.0
  
  # Code Generation
  build_runner: ^2.4.8
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
